### ISSUE TITLE
Practice Nested Repeaters

### ISSUE THREAD

**Issue by cnowitskey17** [cnowitskey17/DMIT-2018-Workbook#2]
Create a page that shows our supplies and the products they offer. I will need to see info in the following structure

- supplier:
   -company name
   -contact name
   -phone number
   
    -product summary
    -product name
   -category name
   -unit price
   -qty/unit

#TASKS

- [ ] Create LINQ query in linqpad
- [ ] create classes for the read model
- [ ] Copy/adapt linqpad query to bll method
- [ ] create page with nested repeater
